### ISSUE TITLE
Cound not find LCD2USB device

### ISSUE THREAD

**Issue by knoesterpitter** [harbaum/LCD2USB#5]
I would be happy, if I get the software running. 
My Environment: 
Raspberry Pi Model B Rev 2
Linux rasp1-buster 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
I did:
sudo pip install lcd2usb
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: lcd2usb in /usr/local/lib/python2.7/dist-packages (1.2)
Requirement already satisfied: libusb1 in /usr/local/lib/python2.7/dist-packages (from lcd2usb) (1.7.1)

Now the 1602 RGB LCD is connected with the USB-Port

sudo python usblcd.py
Traceback (most recent call last):
  File "usblcd.py", line 9, in <module>
    lcd = LCD()
  File "/usr/local/lib/python2.7/dist-packages/lcd2usb.py", line 69, in __init__
    raise LCD2USBNotFound()
lcd2usb.LCD2USBNotFound: Cound not find LCD2USB device.

I am shure its my fault. But I dont know where to look.
I hope, somebody has a soultion or a hint (or a URL).
Many thanks in advance.

**Comment by ConiKost** [comment]
Well, does you kernel has the needed modules, so your lcd module will show up as lcd device? What does ```lsusb``` show?

**Comment by BlackMage2** [comment]
I also have a lcd2usb device that doesn't work. it is also not listed in lsusb. probably a defective controller I would say

**Comment by ConiKost** [comment]
Yeah, sound so. It should be listed at least in lsusb.

**Comment by harbaum** [comment]
Does the display itself show any signs of life? It should at least power up when connected to USB.

**Comment by BlackMage2** [comment]
yes, in display is shown "LCD2USB V1.09"

But that's no use to me if the display isn't accessible at all

i have opened a case at the aliexpress seller
I'm curious about the result

in first it was declined with 'can you check it again', I submitted the same request again

aliexpress is bullshit, if you have received defective HW is very difficult to prove. the seller always has rights and video upload on aliexpress does not work(the seller really wants a video)
and the video upload doesn't work on aliexpress, idk why

all common video sites are blocked, I could use possible youku, but that's too complicated for me(chinese site)

edit:
ohh now: surprisingly, the return has been approved, after intervention by aliexpress.
now i wait for the return adress or i gets approved in 72h

edit2:
now finally I'm not sending it back because it would be way too expensive
